# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

apiVersion: autoscaling/v2
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale
# automatische Skalierung fuer die Anzahl der Pods basierend auf der CPU-Auslastung oder durch Metriken, die von der
# Anwendung bereitgestellt werden
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "axa.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "axa.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "axa.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization:  {{ .Values.autoscaling.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization:  {{ .Values.autoscaling.memoryUtilizationPercentage }}
