# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#             http://localhost:9411/zipkin
#             docker compose exec zipkin ash
#           docker compose down

services:
  zipkin:
    # Image basierend auf nginx als Webserver
    #image: openzipkin/zipkin:3.4.0
    #image: openzipkin/zipkin:3.3.0
    #image: openzipkin/zipkin:3.2.1
    #image: openzipkin/zipkin:3.1.1
    image: openzipkin/zipkin:3.1.0
    ports:
      - published: 9411
        target: 9411
    container_name: zipkin
    #extra_hosts: ['host.docker.internal']
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 512M
